BEGIN;

DROP TABLE IF EXISTS public.user_mcp_tools CASCADE;
DROP TABLE IF EXISTS public.user_mcp_servers CASCADE;
DROP TABLE IF EXISTS public.user_preferences CASCADE;
DROP TABLE IF EXISTS public.user_locations CASCADE;
DROP TABLE IF EXISTS public.generated_image_assets CASCADE;
DROP TABLE IF EXISTS public.conversation_events CASCADE;
DROP TABLE IF EXISTS public.conversation_shares CASCADE;
DROP TABLE IF EXISTS public.account_action_tokens CASCADE;
DROP TABLE IF EXISTS public.audit_events CASCADE;
DROP TABLE IF EXISTS public.billing_redemption_code_disables CASCADE;
DROP TABLE IF EXISTS public.billing_redemption_codes CASCADE;
DROP TABLE IF EXISTS public.billing_tool_prices CASCADE;
DROP TABLE IF EXISTS public.billing_usage_events CASCADE;
DROP TABLE IF EXISTS public.billing_transactions CASCADE;
DROP TABLE IF EXISTS public.billing_accounts CASCADE;
DROP TABLE IF EXISTS public.attachments CASCADE;
DROP TABLE IF EXISTS public.sandboxes CASCADE;
DROP TABLE IF EXISTS public.tool_calls CASCADE;
DROP TABLE IF EXISTS public.outbox_events CASCADE;
DROP TABLE IF EXISTS public.turn_runs CASCADE;
DROP TABLE IF EXISTS public.conversation_initial_turns CASCADE;
DROP TABLE IF EXISTS public.messages CASCADE;
DROP TABLE IF EXISTS public.turns CASCADE;
DROP TABLE IF EXISTS public.context_heads CASCADE;
DROP TABLE IF EXISTS public.conversations CASCADE;
DROP TABLE IF EXISTS public.smtp_settings CASCADE;
DROP TABLE IF EXISTS public.model_settings CASCADE;
DROP TABLE IF EXISTS public.model_price_versions CASCADE;
DROP TABLE IF EXISTS public.models CASCADE;
DROP TABLE IF EXISTS public.provider_credentials CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

DROP FUNCTION IF EXISTS public.enforce_user_attachment_storage();
DROP FUNCTION IF EXISTS public.enforce_model_price_lifecycle();
DROP FUNCTION IF EXISTS public.reject_immutable_row_change();
DROP FUNCTION IF EXISTS public.set_updated_at();

COMMIT;
